name: 機能追加
description: プロダクトへ機能追加する際のイシューテンプレートです
title: "【機能追加】"
labels: ["enhancement"]
projects: ["akagire/3"]
body:
  - type: markdown
    attributes:
      value: |
        - 【任意】とある項目以外は全て必須です
        - 必要に応じてラベルを追加してもよいですが `enhancement` ラベルは外さないでください
  - type: input
    id: summary
    attributes:
      label: 機能の概要
      description: どのような機能が必要ですか？
      placeholder: xxx を xxx できるようにする
    validations:
      required: true
  - type: input
    id: user-story
    attributes:
      label: ユーザーストーリー
      description: どんなユーザーのどんな課題を解消しますか？
      placeholder: xxx が xxx した時、 xxx という課題・ニーズがあるため xxx できるようにする。
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: 【任意】このイシューが着手可能になる条件
      description: この機能を実装するために必要な条件はありますか？
      placeholder: "- [ ] xxx の調査が完了している"
    validations:
      required: true
  - type: textarea
    id: subtasks
    attributes:
      label: 【任意】サブタスク
      description: 後から編集、追記して構いません。細分化は、開発者やデザイナーが行うことを推奨します。
      placeholder: "- [ ] xxx を xxx にする"
    validations:
      required: false
